### ISSUE TITLE
    Error executing action `run` on resource 'ruby_block[load_tests_and_register_handler]'

### ISSUE THREAD

**Issue by damm** [btm/minitest-handler-cookbook#78]
Chef Version 13.0.113 

```    ================================================================================
    Error executing action `run` on resource 'ruby_block[load_tests_and_register_handler]'
    ================================================================================

    NoMethodError
    -------------
    undefined method `each' for nil:NilClass

    Cookbook Trace:
    ---------------
    /tmp/kitchen/cache/cookbooks/minitest-handler/libraries/test_loader.rb:235:in `cookbook_file_paths'
    /tmp/kitchen/cache/cookbooks/minitest-handler/libraries/test_loader.rb:247:in `cookbook_file_names'
    /tmp/kitchen/cache/cookbooks/minitest-handler/libraries/test_loader.rb:220:in `all_test_files'
    /tmp/kitchen/cache/cookbooks/minitest-handler/libraries/test_loader.rb:206:in `test_files'
    /tmp/kitchen/cache/cookbooks/minitest-handler/libraries/test_loader.rb:35:in `block in load_tests'
    /tmp/kitchen/cache/cookbooks/minitest-handler/libraries/test_loader.rb:10:in `each'
    /tmp/kitchen/cache/cookbooks/minitest-handler/libraries/test_loader.rb:10:in `load_tests'
    /tmp/kitchen/cache/cookbooks/minitest-handler/recipes/default.rb:52:in `block (2 levels) in from_file'

    Resource Declaration:
    ---------------------
    # In /tmp/kitchen/cache/cookbooks/minitest-handler/recipes/default.rb

     50: ruby_block 'load_tests_and_register_handler' do
     51:   block do
     52:     load_tests
     53:     register_handler
     54:   end
     55: end

    Compiled Resource:
    ------------------
    # Declared in /tmp/kitchen/cache/cookbooks/minitest-handler/recipes/default.rb:50:in `from_file'

    ruby_block("load_tests_and_register_handler") do
      action [:run]
      default_guard_interpreter :default
      block_name "load_tests_and_register_handler"
      declared_type :ruby_block
      cookbook_name "minitest-handler"
      recipe_name "default"
      block #<Proc:0x000000041ca968@/tmp/kitchen/cache/cookbooks/minitest-handler/recipes/default.rb:51>
    end

    System Info:
    ------------
    chef_version=13.0.113
    platform=ubuntu
    platform_version=16.04
    ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
    program_name=chef-client worker: ppid=3195;start=23:06:03;
    executable=/opt/chef/bin/chef-client

[2017-04-10T23:06:07+00:00] INFO: Running queued delayed notifications before re-raising exception
[2017-04-10T23:06:07+00:00] INFO: Running queued delayed notifications before re-raising exception
[2017-04-10T23:06:07+00:00] DEBUG: Re-raising exception: NoMethodError - ruby_block[load_tests_and_register_handler] (minitest-handler::default line 50) had an error: NoMethodError: undefined method `each' for nil:NilClass
/tmp/kitchen/cache/cookbooks/minitest-handler/libraries/test_loader.rb:235:in `cookbook_file_paths'
  /tmp/kitchen/cache/cookbooks/minitest-handler/libraries/test_loader.rb:247:in `cookbook_file_names'
  /tmp/kitchen/cache/cookbooks/minitest-handler/libraries/test_loader.rb:220:in `all_test_files'
  /tmp/kitchen/cache/cookbooks/minitest-handler/libraries/test_loader.rb:206:in `test_files'
  /tmp/kitchen/cache/cookbooks/minitest-handler/libraries/test_loader.rb:35:in `block in load_tests'
  /tmp/kitchen/cache/cookbooks/minitest-handler/libraries/test_loader.rb:10:in `each'
  /tmp/kitchen/cache/cookbooks/minitest-handler/libraries/test_loader.rb:10:in `load_tests'
```

**Comment by unhuman** [comment]
+1
